apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "pinta.fullname" . }}-controller-serviceaccount
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ template "pinta.fullname" . }}-controller-clusterrole
rules:
  - apiGroups: [ "apiextensions.k8s.io" ]
    resources: [ "customresourcedefinitions" ]
    verbs: [ "create", "get", "list", "watch", "delete" ]
  - apiGroups: [ "pinta.qed.usc.edu" ]
    resources: [ "pintajobs" ]
    verbs: [ "get", "list", "watch", "update", "delete" ]
  - apiGroups: [ "pinta.qed.usc.edu" ]
    resources: [ "pintajobs/status" ]
    verbs: [ "update", "patch" ]
  - apiGroups: [ "" ]
    resources: [ "events" ]
    verbs: [ "create", "list", "watch", "update", "patch" ]
  - apiGroups: [ "batch.volcano.sh" ]
    resources: [ "jobs" ]
    verbs: [ "create", "get", "list", "watch", "update", "delete" ]
  - apiGroups: [ "" ]
    resources: [ "nodes" ]
    verbs: [ "get", "list", "watch" ]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ template "pinta.fullname" . }}-controller-clusterrolebinding
subjects:
  - kind: ServiceAccount
    name: {{ template "pinta.fullname" . }}-controller-serviceaccount
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: {{ template "pinta.fullname" . }}-controller-clusterrole
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "pinta.fullname" . }}-controller
  labels:
    app: {{ template "pinta.fullname" . }}-controller
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ template "pinta.fullname" . }}-controller
  template:
    metadata:
      labels:
        app: {{ template "pinta.fullname" . }}-controller
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/path: /metrics
        prometheus.io/port: "8080"
    spec:
      serviceAccountName: {{ template "pinta.fullname" . }}-controller-serviceaccount
      containers:
        - name: {{ template "pinta.fullname" . }}-controller
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command:
            - /bin/pinta-controller
          args:
            - --logtostderr
            - -v=4
            - 2>&1
          ports:
            - containerPort: 8080
              name: metrics
              protocol: TCP
