apiVersion: v1
kind: PersistentVolume
metadata:
  name: data-{{ template "pinta.fullname" . }}-provisioner-0
spec:
  capacity:
    storage: {{ index .Values "nfs-server-provisioner" "persistence" "size" }}
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: {{ .Values.pv.path }}
  claimRef:
    name: data-{{ template "pinta.fullname" . }}-provisioner-0
    namespace: {{ .Release.Namespace }}
