---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: docker-registry
  namespace: pinta-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: docker-registry
  template:
    metadata:
      labels:
        app: docker-registry
    spec:
      volumes:
        - name: registry-pv-storage
          persistentVolumeClaim:
            claimName: registry-pv-claim
      containers:
        - name: docker-registry
          image: registry
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 5000
              protocol: TCP
          volumeMounts:
            - name: registry-pv-storage
              mountPath: /var/lib/registry
---
apiVersion: v1
kind: Service
metadata:
  name: registry-service
  namespace: pinta-system
  labels:
    app: docker-registry
spec:
  type: NodePort
  selector:
    app: docker-registry
  ports:
    - port: 5000
      targetPort: 5000
      nodePort: 30007
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: docker-insecure-registries
data:
  daemon.json: |
    {
      "insecure-registries": ["registry-service", "registry-service.pinta-system.svc", "registry-service:5000", "registry-service.pinta-system.svc:5000"]
    }
