apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: pintajobs.pinta.qed.usc.edu
spec:
  group: pinta.qed.usc.edu
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                type:
                  type: string
                volumes:
                  type: array
                  items:
                    type: object
                    x-kubernetes-preserve-unknown-fields: true
                master:
                  type: object
                  x-kubernetes-preserve-unknown-fields: true
                replica:
                  type: object
                  x-kubernetes-preserve-unknown-fields: true
            status:
              type: object
              properties:
                state:
                  type: string
                lastTransitionTime:
                  format: date-time
                  type: string
                numMasters:
                  format: int32
                  type: integer
                numReplicas:
                  format: int32
                  type: integer
      subresources:
        status: {}
      additionalPrinterColumns:
        - name: Type
          type: string
          jsonPath: .spec.type
        - name: Masters
          type: integer
          jsonPath: .status.numMasters
        - name: Replicas
          type: integer
          jsonPath: .status.numReplicas
        - name: Status
          type: string
          jsonPath: .status.state
  scope: Namespaced
  names:
    kind: PintaJob
    singular: pintajob
    plural: pintajobs
    shortNames:
      - ptjob
      - pj
