apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: pintajobs.pinta.qed.usc.edu
spec:
  group: pinta.qed.usc.edu
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                type:
                  type: string
                master:
                  type: object
                  x-kubernetes-preserve-unknown-fields: true
                replica:
                  type: object
                  x-kubernetes-preserve-unknown-fields: true
                numMasters:
                  format: int32
                  type: integer
                numReplicas:
                  format: int32
                  type: integer
            status:
              type: string
      subresources:
        status: {}
  scope: Namespaced
  names:
    kind: PintaJob
    singular: pintajob
    plural: pintajobs
    shortNames:
      - ptjob
      - pj
