apiVersion: pinta.qed.usc.edu/v1
kind: PintaJob
metadata:
  name: example-pintajob
  annotations:
    pinta.qed.usc.edu/custom-fields: |
      numMasters: 1
      numReplicas: 1
      batchSize: 100
      iterations: 500
      throughput:
      - 1
      - 2
      - 3
      - 3.8
      - 4.6
      - 4.9
      - 4.9
      - 5
spec:
  type: ps-worker  # ps-worker, mpi, symmetric, image-builder
  master:
#    nodeType: cpu-1
    spec:
      containers:
        - name: test
          image: ubuntu:latest
          workingDir: /
          command:
            - sh
            - -c
            - |
              echo 'This is PS';
              sleep 3600;
      restartPolicy: OnFailure
    resources:
      node: "1"
  replica:
#    nodeType: cpu-2
    spec:
      containers:
        - name: test
          image: ubuntu:latest
          workingDir: /
          command:
            - sh
            - -c
            - |
              echo 'This is worker';
              sleep 3600;
      restartPolicy: OnFailure
    resources:
      node: "1"
