apiVersion: pinta.qed.usc.edu/v1
kind: PintaJob
metadata:
  name: example-pintajob
spec:
  type: ps-worker  # ps-worker, mpi, symmetric, image-builder
  master:
    spec:
      containers:
        - name: test
          image: ubuntu:latest
          workingDir: /
          command:
            - sh
            - -c
            - |
              echo 'This is PS';
              sleep 120;
          resources:
            requests:
              cpu: "8"
      restartPolicy: OnFailure
  replica:
    spec:
      containers:
        - name: test
          image: ubuntu:latest
          workingDir: /
          command:
            - sh
            - -c
            - |
              echo 'This is worker';
              sleep 60;
          resources:
            requests:
              cpu: "8"
      restartPolicy: OnFailure
  numMasters: 1
  numReplicas: 2
